version: '3.2'
services:
  springapp:
    build:
      context: .
      args:
        JAR_FILE: "${JAR_FILE}"
    container_name: spring-boot-test-docker
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: "${CONFIG_DIR:-./config}"
        target: /config

