spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    encoding: utf-8
    user: ac
    password: 123123
    url: jdbc:postgresql://localhost:5432/test?useUnicode=true&connectionCollation=utf8_general_ci&characterSetResults=utf8&characterEncoding=utf-8
    # connection
  datasource:
    username: ac
    password: 123123
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test?useUnicode=true&connectionCollation=utf8_general_ci&characterSetResults=utf8&characterEncoding=utf-8